<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQH72Sxh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQH72Sxh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQH72Sxh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQH72Sxh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQH72Sxh\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QH72Sxh',
    'container.build_id' => '99f79175',
    'container.build_time' => 1539206149,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQH72Sxh');
