<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYLMbu7Z\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYLMbu7Z/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYLMbu7Z.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYLMbu7Z\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYLMbu7Z\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YLMbu7Z',
    'container.build_id' => 'b19f08ad',
    'container.build_time' => 1540499590,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYLMbu7Z');
