<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXiIPs3I\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXiIPs3I/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXiIPs3I.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXiIPs3I\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXiIPs3I\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XiIPs3I',
    'container.build_id' => '997f09cf',
    'container.build_time' => 1539416914,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXiIPs3I');
